version: '3.8'
services:
    php-project:
        container_name: php-project
        image: php-project:1
        ports:
            - 80:80
    # jenkins:
    #   image: jenkins/jenkins:lts
    #   user: root
    #   ports: 
    #    - 8081:80
    #   container_name: jenkins
    #   volumes: 
    #     - ~/jenkins:/var/jenkins_home
    #     - /var/run/docker.sock:/var/run/docker.sock
    #     - /usr/local/bin/docker:/usr/local/bin/docker
    # nodejs: 
    #     build: .
    #     command: node index.js
    #     volumes:
    #        - /Users/basselsaadeareeba/Desktop/DevopsProjet/src/
    #        - /Users/basselsaadeareeba/Desktop/DevopsProjet/src/node_modules
    #     ports:
    #       - 3000:3000
    #     depends_on:
    #       - db

